var spotfiy_genres = {
    "2-step/british garage": true,
    "aboriginal folk": true,
    "aboriginal rock": true,
    "acadian": true,
    "acappella": true,
    "acid folk": true,
    "acid house": true,
    "acid jazz": true,
    "acid rock": true,
    "acid techno": true,
    "acoustic blues": true,
    "acoustic chicago blues": true,
    "acoustic louisiana blues": true,
    "acoustic memphis blues": true,
    "acoustic new orleans blues": true,
    "acoustic texas blues": true,
    "adult alternative": true,
    "adult alternative pop/rock": true,
    "adult contemporary": true,
    "african folk": true,
    "african jazz": true,
    "afro-beat": true,
    "afro-brazilian": true,
    "afro-colombian": true,
    "afro-cuban": true,
    "afro-cuban jazz": true,
    "afro peruvian": true,
    "afro-pop": true,
    "album rock": true,
    "al-jil": true,
    "alternative": ["alternative pop/rock"],
    "alternative ccm": true,
    "alternative country": true,
    "alternative country-rock": true,
    "alternative dance": true,
    "alternative folk": true,
    "alternative metal": true,
    "alternative pop/rock": true,
    "alternative rock": ["alternative pop/rock"],
    "alternative rap": true,
    "alternative singer/songwriter": true,
    "ambient": true,
    "ambient breakbeat": true,
    "ambient dub": true,
    "ambient house": true,
    "ambient pop": true,
    "ambient techno": true,
    "americana": true,
    "american jewish pop": true,
    "american popular song": true,
    "american punk": true,
    "american trad rock": true,
    "american underground": true,
    "am pop": true,
    "anarchist punk": true,
    "andalus classical": true,
    "andean folk": true,
    "anime music": true,
    "anti-folk": true,
    "apala": true,
    "appalachian folk": true,
    "arena rock": true,
    "argentine folk": true,
    "armenian": true,
    "armenian folk": true,
    "asian folk": true,
    "asian pop": true,
    "atonal": true,
    "audiobooks": true,
    "aussie rock": true,
    "austropop": true,
    "avant-garde": true,
    "avant-garde jazz": true,
    "avant-prog": true,
    "bachata": true,
    "bakersfield sound": true,
    "ballads": true,
    "ballroom dance": true,
    "banda": true,
    "bar band": true,
    "barbershop quartet": true,
    "baroque": true,
    "baroque pop": true,
    "bass music": true,
    "bava": true,
    "beach": true,
    "beat poetry": true,
    "beguine": true,
    "beguine moderne": true,
    "beguine vide": true,
    "belair": true,
    "bel canto opera": true,
    "belly dancing": true,
    "bhangra": true,
    "big band": true,
    "big band latino": true,
    "big beat": true,
    "bikutsi": true,
    "black gospel": true,
    "blaxploitation": true,
    "bluebeat": true,
    "blue-eyed soul": true,
    "bluegrass": true,
    "bluegrass-gospel": true,
    "blue humor": true,
    "blues": true,
    "blues gospel": true,
    "blues revival": true,
    "blues-rock": true,
    "bolero": true,
    "bollywood": true,
    "bombara": true,
    "boogaloo": true,
    "boogie rock": true,
    "boogie-woogie": true,
    "bop": true,
    "bossa nova": true,
    "brass band": true,
    "brazilian folk": true,
    "brazilian jazz": true,
    "brazilian pop": true,
    "breakbeat": ["nu breaks","funky breaks","ambient breakbeat"],
    "brill building pop": true,
    "british blues": true,
    "british dance bands": true,
    "british folk": true,
    "british folk-rock": true,
    "british invasion": true,
    "british metal": true,
    "british psychedelia": true,
    "british punk": true,
    "british rap": true,
    "british trad rock": true,
    "britpop": true,
    "broken beat": true,
    "brown-eyed soul": true,
    "bubblegum": true,
    "bulgarian folk": true,
    "c-86": true,
    "cabaret": true,
    "cadence": true,
    "cajun": true,
    "calypso": true,
    "canterbury scene": true,
    "caribbean folk": true,
    "carnatic": true,
    "carnival": true,
    "carols": true,
    "cartoon music": true,
    "cast recordings": true,
    "ccm": true,
    "celebrity": true,
    "celtic": true,
    "celtic folk": true,
    "celtic fusion": true,
    "celtic gospel": true,
    "celtic new age": true,
    "celtic pop": true,
    "celtic rock": true,
    "ceremonial": true,
    "cha-cha": true,
    "chamber jazz": true,
    "chamber music": true,
    "chamber pop": true,
    "changui": true,
    "chant": true,
    "chants": true,
    "chanukah": true,
    "charanga": true,
    "chassidic": true,
    "chicago blues": true,
    "chicago soul": true,
    "children's": true,
    "children's folk": true,
    "children's stories": true,
    "chilean folk": true,
    "chimurenga": true,
    "chinese classical": true,
    "chinese folk": true,
    "chinese pop": true,
    "chinese pop-rock": true,
    "choral": true,
    "choro": true,
    "chouval bwa": true,
    "christian comedy": true,
    "christian metal": true,
    "christian punk": true,
    "christian rap": true,
    "christian rock": true,
    "christmas": true,
    "circus music": true,
    "classical": true,
    "classical crossover": true,
    "classical guitar": true,
    "classical pop": true,
    "classic female blues": true,
    "classic jazz": true,
    "close harmony": true,
    "club/dance": true,
    "cocktail": true,
    "college rock": true,
    "comedy": true,
    "comedy rap": true,
    "comedy rock": true,
    "compas": true,
    "computer music": true,
    "conceptual art": true,
    "conjunto": true,
    "contemporary bluegrass": true,
    "contemporary blues": true,
    "contemporary celtic": true,
    "contemporary country": true,
    "contemporary flamenco": true,
    "contemporary folk": true,
    "contemporary gospel": true,
    "contemporary instrumental": true,
    "contemporary jazz": true,
    "contemporary native american": true,
    "contemporary r&b": true,
    "contemporary reggae": true,
    "contemporary singer/songwriter": true,
    "continental jazz": true,
    "cool": true,
    "corrido": true,
    "country": true,
    "country blues": true,
    "country boogie": true,
    "country comedy": true,
    "country-folk": true,
    "country gospel": true,
    "country-pop": true,
    "country-rock": true,
    "country-soul": true,
    "cowboy": true,
    "cowpunk": true,
    "creative orchestra": true,
    "creole": true,
    "crossover jazz": true,
    "cuatro": true,
    "cuban jazz": true,
    "cuban pop": true,
    "cumbia": true,
    "dance bands": true,
    "dancehall": true,
    "dance-pop": true,
    "dance-rock": true,
    "danzon": true,
    "dark ambient": true,
    "death metal/black metal": true,
    "deep funk": true,
    "deep funk revival": true,
    "deep soul": true,
    "delta blues": true,
    "demonstration/test disc": true,
    "detroit blues": true,
    "detroit rock": true,
    "detroit techno": true,
    "dhrupad": true,
    "dimotiko": true,
    "dirty blues": true,
    "dirty rap": true,
    "dirty south": true,
    "disco": true,
    "dixieland": true,
    "dixieland revival": true,
    "dj": true,
    "djabdong": true,
    "documentary": true,
    "doom metal": true,
    "doo wop": true,
    "downbeat": true,
    "downtempo": true,
    "drama": true,
    "dream pop": true,
    "drill'n'bass": true,
    "drinking songs": true,
    "dub": true,
    "dub poetry": true,
    "dutch pop": true,
    "early american blues": true,
    "early british pop/rock": true,
    "early creative": true,
    "early music": true,
    "east coast blues": true,
    "east coast rap": true,
    "easter": true,
    "eastern europe": true,
    "eastern european pop": true,
    "easy listening": true,
    "easy pop": true,
    "educational": true,
    "egyptian/sudanese music": true,
    "electric blues": true,
    "electric chicago blues": true,
    "electric country blues": true,
    "electric delta blues": true,
    "electric harmonica blues": true,
    "electric memphis blues": true,
    "electric texas blues": true,
    "electro": true,
    "electro-acoustic": true,
    "electro-industrial": true,
    "electro-jazz": true,
    "electronic": true,
    "electronica": true,
    "electro-techno": true,
    "emo": true,
    "enka": true,
    "environmental": true,
    "erotica": true,
    "ethiopian pop": true,
    "ethnic": true,
    "ethnic comedy": true,
    "ethnic fusion": true,
    "euro-dance": true,
    "european folk": true,
    "euro-pop": true,
    "euro-rock": true,
    "exercise": true,
    "exotica": true,
    "experimental": true,
    "experimental ambient": true,
    "experimental big band": true,
    "experimental dub": true,
    "experimental electro": true,
    "experimental jungle": true,
    "experimental rock": true,
    "experimental techno": true,
    "fado": true,
    "fairy tales": true,
    "fantasy": true,
    "field recordings": true,
    "fight songs": true,
    "film music": true,
    "finger-picked guitar": true,
    "finnish folk": true,
    "flamenco": true,
    "folk": true,
    "folk-blues": true,
    "folk-jazz": true,
    "folklore": true,
    "folk-pop": true,
    "folk revival": true,
    "folk-rock": true,
    "folksongs": true,
    "foreign language rap": true,
    "foreign language rock": true,
    "forro": true,
    "frat rock": true,
    "freakbeat": true,
    "free folk": true,
    "free funk": true,
    "free improvisation": true,
    "free jazz": true,
    "freestyle": true,
    "french chanson": true,
    "french folk": true,
    "french pop": true,
    "french rock": true,
    "fuji": true,
    "funk": true,
    "funk metal": true,
    "funky breaks": true,
    "fusion": true,
    "gabba": true,
    "gamelan": true,
    "game sounds": true,
    "gangsta rap": true,
    "garage/house": true,
    "garage punk": true,
    "garage rap/grime": true,
    "garage rock": true,
    "garage rock revival": true,
    "gay": true,
    "gay comedy": true,
    "gay country": true,
    "gay gospel": true,
    "georgian choir": true,
    "german liedermacher": true,
    "german schlager": true,
    "german volksmusik": true,
    "g-funk": true,
    "giddha": true,
    "girl group": true,
    "glam rock": true,
    "glitch": true,
    "glitter": true,
    "goa trance": true,
    "go-go": true,
    "golden age": true,
    "gospel": true,
    "gospel choir": true,
    "goth metal": true,
    "goth rock": true,
    "greek folk": true,
    "gregorian chant": true,
    "grindcore": true,
    "grunge": true,
    "grupero": true,
    "guaguanc√≥": true,
    "guitar virtuoso": true,
    "gwo ka": true,
    "gypsy": true,
    "hair metal": true,
    "halloween": true,
    "happy hardcore": true,
    "hard bop": true,
    "hardcore punk": true,
    "hardcore rap": true,
    "hardcore techno": true,
    "hard rock": true,
    "harmonica blues": true,
    "harmony vocal group": true,
    "hawaiian pop": true,
    "healing": true,
    "heartland rock": true,
    "heavy metal": true,
    "hebrew": true,
    "highlife": true,
    "hi-nrg": true,
    "hip-hop": true,
    "hip hop": ['hip-hop'],
    "holiday": true,
    "hong kong pop": true,
    "honky tonk": true,
    "hot jazz": true,
    "hot rod": true,
    "hot rod revival": true,
    "house": true,
    "hungarian folk": true,
    "hymns": true,
    "idm": true,
    "illbient": true,
    "impressionist": true,
    "improvisation": true,
    "indian classical": true,
    "indian folk": true,
    "indian pop": true,
    "indie electronic": true,
    "indie pop": true,
    "indie rock": true,
    "indie": ["indie rock"],
    "indigenous": true,
    "indipop": true,
    "industrial": true,
    "industrial dance": true,
    "industrial drum'n'bass": true,
    "industrial metal": true,
    "inspirational": true,
    "instructional": true,
    "instrumental country": true,
    "instrumental gospel": true,
    "instrumental pop": true,
    "instrumental rock": true,
    "international folk": true,
    "international pop": true,
    "interview": true,
    "inuit": true,
    "iran-classical": true,
    "irish folk": true,
    "italian folk": true,
    "italian pop": true,
    "jaipongan": true,
    "jam bands": true,
    "jangle pop": true,
    "japanese orchestral": true,
    "japanese pop": true,
    "japanese rock": true,
    "jazz": true,
    "jazz blues": true,
    "jazz-funk": true,
    "jazz-house": true,
    "jazz-pop": true,
    "jazz-rap": true,
    "jazz-rock": true,
    "jesus rock": true,
    "jewish folk": true,
    "jewish music": true,
    "jibaro": true,
    "jit": true,
    "jive": true,
    "joik": true,
    "jug band": true,
    "juju": true,
    "juke joint blues": true,
    "jump blues": true,
    "jungle/drum'n'bass": true,
    "drum and bass": [ "jungle/drum'n'bass" ],
    "dnb": [ "jungle/drum'n'bass" ],
    "junkanoo": true,
    "kabuki": true,
    "karaoke": true,
    "kayokyoku": true,
    "kecak": true,
    "khmer dance": true,
    "klezmer": true,
    "kora": true,
    "korean pop": true,
    "korean rock": true,
    "kraut rock": true,
    "laika": true,
    "lambada": true,
    "l.a. punk": true,
    "latin": true,
    "latin ccm": true,
    "latin comedy": true,
    "latin dance": true,
    "latin folk": true,
    "latin freestyle": true,
    "latin gospel": true,
    "latin jazz": true,
    "latin pop": true,
    "latin rap": true,
    "latin rock": true,
    "latin soul": true,
    "left-field hip-hop": true,
    "left-field house": true,
    "lo-fi": true,
    "louisiana blues": true,
    "lounge": true,
    "lovers rock": true,
    "lullabies": true,
    "macapat poetry": true,
    "madchester": true,
    "mainstream jazz": true,
    "makossa": true,
    "mambo": true,
    "mantras": true,
    "marabi": true,
    "march": true,
    "marches": true,
    "mariachi": true,
    "math rock": true,
    "mbalax": true,
    "mbaqanga": true,
    "m-base": true,
    "mbira": true,
    "mbube": true,
    "mbuti choral": true,
    "medieval": true,
    "meditation": true,
    "memphis blues": true,
    "memphis soul": true,
    "mento": true,
    "merengue": true,
    "merenhouse": true,
    "merseybeat": true,
    "mexican folk": true,
    "microhouse": true,
    "microsound": true,
    "microtonal": true,
    "middle eastern pop": true,
    "midwest rap": true,
    "military": true,
    "mini jazz": true,
    "minimalism": true,
    "minimal techno": true,
    "minstrel": true,
    "miscellaneous": true,
    "mixed media": true,
    "mod": true,
    "modal music": true,
    "modern acoustic blues": true,
    "modern big band": true,
    "modern composition": true,
    "modern creative": true,
    "modern delta blues": true,
    "modern electric blues": true,
    "modern electric chicago blues": true,
    "modern electric texas blues": true,
    "modern free": true,
    "modern son": true,
    "mod revival": true,
    "mood music": true,
    "moravian folk": true,
    "morna": true,
    "morning radio": true,
    "motown": true,
    "movie themes": true,
    "mpb": true,
    "mugam": true,
    "musette": true,
    "musical comedy": true,
    "musicals": true,
    "musical theater": true,
    "music hall": true,
    "musique actuelle": true,
    "musique concr√®te": true,
    "mystical minimalism": true,
    "nashville sound/countrypolitan": true,
    "nationalist": true,
    "nature": true,
    "neo-bop": true,
    "neo-classical": true,
    "neo-classical metal": true,
    "neo-electro": true,
    "neo-glam": true,
    "neo-prog": true,
    "neo-psychedelia": true,
    "neo-romantic": true,
    "neo-soul": true,
    "neo-traditional": true,
    "neo-traditional folk": true,
    "neo-traditionalist country": true,
    "new acoustic": true,
    "new age": true,
    "new age tone poems": true,
    "newbeat": true,
    "new jack swing": true,
    "new orleans blues": true,
    "new orleans brass bands": true,
    "new orleans jazz": true,
    "new orleans r&b": true,
    "new romantic": true,
    "new traditionalist": true,
    "new wave": true,
    "new wave of british heavy metal": true,
    "new wave/post-punk revival": true,
    "new york blues": true,
    "new york punk": true,
    "new york salsa": true,
    "new zealand rock": true,
    "nissiotiko": true,
    "noh": true,
    "noise": true,
    "noise pop": true,
    "noise-rock": true,
    "norte√±o": true,
    "northern soul": true,
    "norwegian folk": true,
    "nostalgia": true,
    "novelty": true,
    "novelty ragtime": true,
    "no wave": true,
    "nu breaks": true,
    "nueva cancion": true,
    "nueva trova": true,
    "nursery rhymes": true,
    "nyahbinghi": true,
    "obscuro": true,
    "observational humor": true,
    "oi!": true,
    "okinawan pop": true,
    "okinawan traditional": true,
    "old-school rap": true,
    "old-timey": true,
    "omutibo": true,
    "onda grupera": true,
    "opera": true,
    "operettas": true,
    "oratories": true,
    "orchestral": true,
    "orchestral jazz": true,
    "orchestral pop": true,
    "original score": true,
    "outlaw country": true,
    "pachanga": true,
    "paisley underground": true,
    "pan-global": true,
    "party rap": true,
    "party soca": true,
    "peruvian folk": true,
    "philly soul": true,
    "piano blues": true,
    "piedmont blues": true,
    "pipe bands": true,
    "plena": true,
    "poetry": true,
    "political comedy": true,
    "political folk": true,
    "political rap": true,
    "political reggae": true,
    "polka": true,
    "pop": true,
    "pop idol": true,
    "pop-metal": true,
    "pop-rap": true,
    "pop/rock": true,
    "pop-soul": true,
    "pop underground": true,
    "portuguese music": true,
    "post-bop": true,
    "post-disco": true,
    "post-grunge": true,
    "post-hardcore": true,
    "post-minimalism": true,
    "post-punk": true,
    "post-rock/experimental": true,
    "post-romantic": true,
    "power metal": true,
    "power pop": true,
    "praise & worship": true,
    "prank calls": true,
    "prewar blues": true,
    "prewar country blues": true,
    "prewar gospel blues": true,
    "process-generated": true,
    "progressive alternative": true,
    "progressive big band": true,
    "progressive bluegrass": true,
    "progressive country": true,
    "progressive electronic": true,
    "progressive folk": true,
    "progressive house": true,
    "progressive jazz": true,
    "progressive metal": true,
    "progressive trance": true,
    "prog-rock/art rock": true,
    "proto-punk": true,
    "psychedelic": true,
    "psychedelic pop": true,
    "psychedelic soul": true,
    "psychobilly": true,
    "pub rock": true,
    "punk": true,
    "punk blues": true,
    "punk metal": true,
    "punk-pop": true,
    "punk revival": true,
    "pygmy": true,
    "qawwali": true,
    "quadrille": true,
    "quechua": true,
    "queercore": true,
    "quiet storm": true,
    "radio plays": true,
    "radio shows": true,
    "radio works": true,
    "raga": true,
    "ragga": true,
    "ragtime": true,
    "rai": true,
    "rakugo": true,
    "ranchera": true,
    "rap": true,
    "rap-metal": true,
    "rap-rock": true,
    "rapso": true,
    "rave": true,
    "r&b": true,
    "read-along stories": true,
    "reggae": true,
    "reggae gospel": true,
    "reggae-pop": true,
    "reggaeton": true,
    "relaxation": true,
    "rembetika": true,
    "renaissance": true,
    "retro-rock": true,
    "retro-soul": true,
    "retro swing": true,
    "rhumba": true,
    "riot grrrl": true,
    "rock": true,
    "rockabilly": true,
    "rockabilly revival": true,
    "rock en espa√±ol": true,
    "rock & roll": true,
    "rocksteady": true,
    "rodeo": true,
    "romantic": true,
    "roots reggae": true,
    "roots rock": true,
    "russian folk": true,
    "sacred choral": true,
    "sacred vocal": true,
    "sadcore": true,
    "salsa": true,
    "samba": true,
    "satire": true,
    "scandinavian folk": true,
    "scandinavian metal": true,
    "scandinavian pop": true,
    "scottish folk": true,
    "screamo": true,
    "scriptures": true,
    "sea shanties": true,
    "s√©ga": true,
    "self-help": true,
    "shaabi": true,
    "sharki": true,
    "shibuya-kei": true,
    "shinto": true,
    "shock jock": true,
    "shoegaze": true,
    "show tunes": true,
    "sing-along": true,
    "singer/songwriter": true,
    "ska": true,
    "ska-punk": true,
    "ska revival": true,
    "skatepunk": true,
    "sketch comedy": true,
    "skiffle": true,
    "slack-key guitar": true,
    "slide guitar blues": true,
    "slowcore": true,
    "sludge metal": true,
    "smooth jazz": true,
    "smooth reggae": true,
    "smooth soul": true,
    "soca": true,
    "social commentary": true,
    "society dance band": true,
    "soft rock": true,
    "software/sounds": true,
    "solo instrumental": true,
    "son": true,
    "sonero": true,
    "song parody": true,
    "songster": true,
    "sophisti-pop": true,
    "soukous": true,
    "soul": true,
    "soul-blues": true,
    "soul-jazz": true,
    "sound art": true,
    "sound collage": true,
    "sound effects": true,
    "sound sculpture": true,
    "soundtrack": true,
    "soundtracks": true,
    "south african folk": true,
    "south african pop": true,
    "southeast asian music": true,
    "southern gospel": true,
    "southern rap": true,
    "southern rock": true,
    "southern soul": true,
    "space": true,
    "space age pop": true,
    "space rock": true,
    "spanish folk": true,
    "speeches": true,
    "speed metal": true,
    "spiritual": true,
    "spirituals": true,
    "spoken word": true,
    "sports anthems": true,
    "spouge": true,
    "spy music": true,
    "square dance": true,
    "standards": true,
    "standup comedy": true,
    "steel band": true,
    "st. louis blues": true,
    "stoner metal": true,
    "straight-edge": true,
    "stride": true,
    "string bands": true,
    "structured improvisation": true,
    "sunshine pop": true,
    "surf": true,
    "surf revival": true,
    "swamp blues": true,
    "swamp pop": true,
    "swedish folk": true,
    "swedish pop/rock": true,
    "sweet bands": true,
    "swing": true,
    "switzerland folk": true,
    "symphonic black metal": true,
    "synth pop": true,
    "synthpop": ['synth pop'],
    "taarab": true,
    "taiwanese pop": true,
    "tango": true,
    "tape music": true,
    "tech-house": true,
    "techno": true,
    "techno bass": true,
    "techno-dub": true,
    "techno-tribal": true,
    "teen idol": true,
    "teen pop": true,
    "tejano": true,
    "television music": true,
    "texas blues": true,
    "tex-mex": true,
    "thai pop": true,
    "thanksgiving": true,
    "third stream": true,
    "third wave ska revival": true,
    "thrash": true,
    "throat singing": true,
    "timba": true,
    "tin pan alley pop": true,
    "torch songs": true,
    "township jazz": true,
    "traditional": true,
    "traditional bluegrass": true,
    "traditional cajun": true,
    "traditional celtic": true,
    "traditional chinese": true,
    "traditional country": true,
    "traditional european folk": true,
    "traditional folk": true,
    "traditional gospel": true,
    "traditional irish folk": true,
    "traditional japanese": true,
    "traditional korean": true,
    "traditional middle eastern folk": true,
    "traditional native american": true,
    "traditional pop": true,
    "traditional scottish folk": true,
    "trad jazz": true,
    "trance": true,
    "travel": true,
    "tribal-house": true,
    "tribute albums": true,
    "trip-hop": true,
    "tropical": true,
    "tropicalia": true,
    "trot": true,
    "trova": true,
    "truck driving country": true,
    "turkish folk": true,
    "turkish music": true,
    "turntablism": true,
    "tv soundtracks": true,
    "twee pop": true,
    "underground rap": true,
    "uptown soul": true,
    "urban": true,
    "urban blues": true,
    "urban cowboy": true,
    "urban folk": true,
    "vallenato": true,
    "vaudeville": true,
    "vaudeville blues": true,
    "vaudou": true,
    "video": true,
    "video game music": true,
    "vocal": true,
    "vocalese": true,
    "vocal jazz": true,
    "vocal pop": true,
    "waltz": true,
    "wedding music": true,
    "west coast blues": true,
    "west coast jazz": true,
    "west coast rap": true,
    "western swing": true,
    "western swing revival": true,
    "women's": true,
    "work songs": true,
    "world": true,
    "worldbeat": true,
    "world fusion": true,
    "yodeling": true,
    "zouk": true,
    "zydeco": true
}